### ISSUE TITLE
Исправление найденных при проверке ошибок

### ISSUE THREAD

**Issue by mbogatyrev** [intervolga/intervolga.migrato#10]
Доброго времени суток! Пожалуйста, подскажите, как избавиться от подобных ошибок?
https://yadi.sk/i/c49_CVet3RxRGT
https://yadi.sk/i/csDMnq5y3RxPPL

**Comment by xaoc2007** [comment]
не уверен, что такая же проблема
но подобное у нас было, когда у групп не было символьных кодов
Проверьте, что у группы пользователей с ID = 7 есть символьный код

**Comment by arkanif** [comment]
Согласен с  xaoc2007, проблема скорее всего в этом. Приложите результатат выполнение validate -vvv. А так запустите autofix -- должно помочь.

**Comment by mbogatyrev** [comment]
autofix как раз не помогал. У группы с ID=7 был символьный код. Нам всё-равно пришлось переустанавливать Bitrix. После переустановки данных ошибок не возникало. К сожалению, так и не узнали причины возникновения данных ошибок и пути их устранения =_=
