### ISSUE TITLE
Ломается привязка почтовых шаблонов к веб-формам

### ISSUE THREAD

**Issue by shkarupa-alex** [intervolga/intervolga.migrato#14]
В процессе экспорта/импорта почтовые шаблоны удаляются и создаются заново по причине отсутствия вменяемого способа хранения XML_ID.

При этом в веб-формах возникает проблема. Привязка шаблонов сообщений к веб-формам это не только наличие шаблона под определенный тип почтового события, но и вот такой флажок https://www.evernote.com/l/AS_YPwXTHOJA5q6RMNOAk897k7wlaKI5FPE
При импорте он не восстанавливается.

**Comment by arkanif** [comment]
В новой версии будет исправлено
