### ISSUE TITLE
Проверить почем и может ли возникать приведенная ошибка

### ISSUE THREAD

**Issue by shkarupa-alex** [intervolga/intervolga.migrato#15]
PHP Fatal error:  Call to a member function getValue() on null in /data/baltlease/baltlease.ru/docs/local/modules/intervolga.migrato/lib/data/baseuserfieldenum.php on line 77

**Comment by shkarupa-alex** [comment]
PHP 5.6

**Comment by shkarupa-alex** [comment]
------------------------------------------------------
Гость Андрей [сегодня, 17:43]
я зашел на ту строчку и там судя по коду программа не смогла найти запись по xml
$this->findRecord($record->getXmlId())
------------------------------------------------------

**Comment by arkanif** [comment]
Проверяем, спасибо

**Comment by gafk** [comment]
Исправлено в версии 0.8.9.
