### ISSUE TITLE
Кракозябры

### ISSUE THREAD

**Issue by dhffdh** [intervolga/intervolga.migrato#17]
Windows 10 x64 
Комманды на локальной машине
https://yadi.sk/i/FICNZNid3VrfGB
После применения chcp 65001 картинка улучшается, но не до конца. В чем может быть причина?

**Comment by dhffdh** [comment]
phpstorm 2017.3

**Comment by arkanif** [comment]
@dhffdh попробуйте флаги -U и -W, без ковыряния кодировок средствами chcp 65001
