### ISSUE TITLE
Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0

### ISSUE THREAD

**Issue by dmitrymatlah** [intervolga/intervolga.migrato#18]
Здравствуйте!
Поймал ошибку. Версия php 7.1

Выполняется подкоманда ?[34;47mОбновление urlrewrite.php?[39;49m
?[31mПри выполнении команды произошла ошибка (Класс: Bitrix\Main\DB\SqlQueryException)?[39m
?[31mMysql query error: (2006) MySQL server has gone away (Код ошибки: 400)?[39m
?[34;47mСтек вызова:?[39;49m
## path\to\project\bitrix\modules\main\lib\db\mysqliconnection.php(137)
#0 path\to\project\bitrix\modules\main\lib\db\connection.php(330): Bitrix\Main\DB\MysqliConnection->queryInternal('INSERT INTO `b_...', Array, N
ULL)
#1 path\to\project\bitrix\modules\main\lib\db\connection.php(379): Bitrix\Main\DB\Connection->query('INSERT INTO `b_...', NULL)
#2 path\to\project\bitrix\modules\main\lib\db\connection.php(454): Bitrix\Main\DB\Connection->queryExecute('INSERT INTO `b_...')
#3 path\to\project\bitrix\modules\main\lib\entity\datamanager.php(679): Bitrix\Main\DB\Connection->add('b_component_par...', Array, 'ID')
#4 path\to\project\bitrix\modules\main\lib\urlrewriter.php(437): Bitrix\Main\Entity\DataManager::add(Array)
#5 path\to\project\bitrix\modules\main\lib\urlrewriter.php(388): Bitrix\Main\UrlRewriter::reindexFile('s1', 'E:\\_open_server...', '/bitrix/modu
les...', NULL)
#6 path\to\project\bitrix\modules\main\lib\urlrewriter.php(370): Bitrix\Main\UrlRewriter::recursiveReindex('E:\\_open_server...', '/bitrix/modul
es...', Array, 0, Array)
#7 path\to\project\bitrix\modules\main\lib\urlrewriter.php(370): Bitrix\Main\UrlRewriter::recursiveReindex('E:\\_open_server...', '/bitrix/modul
es...', Array, 0, Array)
#8 path\to\project\bitrix\modules\main\lib\urlrewriter.php(370): Bitrix\Main\UrlRewriter::recursiveReindex('E:\\_open_server...', '/bitrix/modul
es', Array, 0, Array)
#9 path\to\project\bitrix\modules\main\lib\urlrewriter.php(370): Bitrix\Main\UrlRewriter::recursiveReindex('E:\\_open_server...', '/bitrix', Arr
ay, 0, Array)
#10 path\to\project\bitrix\modules\main\lib\urlrewriter.php(328): Bitrix\Main\UrlRewriter::recursiveReindex('E:\\_open_server...', '/', Array, 0
, Array)
#11 path\to\project\bitrix\modules\main\classes\general\urlrewriter.php(104): Bitrix\Main\UrlRewriter::reindexAll(0, Array)
#12 path\to\project\bitrix\modules\intervolga.migrato\lib\tool\console\command\urlrewritecommand.php(27): CUrlRewriter::ReIndexAll()
#13 path\to\project\bitrix\modules\intervolga.migrato\lib\tool\console\command\urlrewritecommand.php(20): Intervolga\Migrato\Tool\Console\Comman
d\UrlRewriteCommand->urlRewrite()
#14 path\to\project\bitrix\modules\intervolga.migrato\lib\tool\console\command\basecommand.php(57): Intervolga\Migrato\Tool\Console\Command\UrlR
ewriteCommand->executeInner()
#15 path\to\project\bitrix\modules\intervolga.migrato\vendor\symfony\console\Command\Command.php(255): Intervolga\Migrato\Tool\Console\Command\B
aseCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 path\to\project\bitrix\modules\intervolga.migrato\lib\tool\console\command\basecommand.php(122): Symfony\Component\Console\Command\Command->
run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 path\to\project\bitrix\modules\intervolga.migrato\lib\tool\console\command\importcommand.php(38): Intervolga\Migrato\Tool\Console\Command\Ba
seCommand->runSubcommand('urlrewrite')
#18 path\to\project\bitrix\modules\intervolga.migrato\lib\tool\console\command\basecommand.php(57): Intervolga\Migrato\Tool\Console\Command\Impo
rtCommand->executeInner()
#19 path\to\project\bitrix\modules\intervolga.migrato\vendor\symfony\console\Command\Command.php(255): Intervolga\Migrato\Tool\Console\Command\B
aseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 path\to\project\bitrix\modules\intervolga.migrato\vendor\symfony\console\Application.php(829): Symfony\Component\Console\Command\Command->ru
n(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 path\to\project\bitrix\modules\intervolga.migrato\vendor\symfony\console\Application.php(191): Symfony\Component\Console\Application->doRunC
ommand(Object(Intervolga\Migrato\Tool\Console\Command\ImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 path\to\project\bitrix\modules\intervolga.migrato\vendor\symfony\console\Application.php(122): Symfony\Component\Console\Application->doRun(
Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 path\to\project\bitrix\modules\intervolga.migrato\lib\tool\page.php(16): Symfony\Component\Console\Application->run(Object(Symfony\Component
\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 path\to\project\bitrix\modules\intervolga.migrato\tools\run.php(26): Intervolga\Migrato\Tool\Page::run()
#25 {main}

Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0

Call Stack:
    0.0003     357848   1. {main}() path\to\project\bitrix\modules\intervolga.migrato\tools\run.php:0
    0.1937   15842952   2. Intervolga\Migrato\Tool\Page::run() path\to\project\bitrix\modules\intervolga.migrato\tools\run.php:26
    0.2972   20536872   3. Intervolga\Migrato\Tool\Console\Application->run() path\to\project\bitrix\modules\intervolga.migrato\lib\tool\page.ph
p:16
    0.5637   20647552   4. Intervolga\Migrato\Tool\Console\Application->doRun() path\to\project\bitrix\modules\intervolga.migrato\vendor\symfony
\console\Application.php:122
    0.5639   20647552   5. Intervolga\Migrato\Tool\Console\Application->doRunCommand() path\to\project\bitrix\modules\intervolga.migrato\vendor\
symfony\console\Application.php:191
    0.5640   20647552   6. Intervolga\Migrato\Tool\Console\Command\ImportCommand->run() \bitrix\modules\intervolga.migrato\vendor
\symfony\console\Application.php:829
    0.5645   20716416   7. Intervolga\Migrato\Tool\Console\Command\ImportCommand->execute() path\to\project\bitrix\modules\intervolga.migrato\ve
ndor\symfony\console\Command\Command.php:255
    0.6006   21007208   8. Intervolga\Migrato\Tool\Console\Command\ImportCommand->executeInner() path\to\project\bitrix\modules\intervolga.migra
to\lib\tool\console\command\basecommand.php:57
   28.9626   55282456   9. Intervolga\Migrato\Tool\Console\Command\ImportCommand->runSubcommand() path\to\project\bitrix\modules\intervolga.migr
ato\lib\tool\console\command\importcommand.php:38
   28.9628   55282888  10. Intervolga\Migrato\Tool\Console\Command\UrlRewriteCommand->run() path\to\project\bitrix\modules\intervolga.migrato\li
b\tool\console\command\basecommand.php:122
   28.9631   55285256  11. Intervolga\Migrato\Tool\Console\Command\UrlRewriteCommand->execute() path\to\project\bitrix\modules\intervolga.migrat
o\vendor\symfony\console\Command\Command.php:255
  537.9697   55737392  12. Intervolga\Migrato\Tool\Console\Logger->handle() path\to\project\bitrix\modules\intervolga.migrato\lib\tool\console\c
ommand\basecommand.php:61
  537.9887   55737072  13. CAllMain::{closure:path\to\project\bitrix\modules\main\classes\general\main.php:3407-3414}() E:\_open_server_5_2_8\OS
Panel\domains\cable-online.loc\bitrix\modules\main\classes\general\main.php:0
  537.9887   55737104  14. ob_end_flush() path\to\project\bitrix\modules\main\classes\general\main.php:3412
  537.9887   55737168  15. CMain->EndBufferContent() path\to\project\bitrix\modules\main\classes\general\main.php:3412
  537.9923   55776976  16. CMain->GetSpreadCookieHTML() path\to\project\bitrix\modules\main\classes\general\main.php:3168
  537.9923   55777376  17. CMain->GetSpreadCookieUrls() path\to\project\bitrix\modules\main\classes\general\main.php:2805
  537.9925   55778072  18. CAllSite::GetList() path\to\project\bitrix\modules\main\classes\general\main.php:2866
  537.9927   55780208  19. CDatabase->Query() path\to\project\bitrix\modules\main\classes\general\main.php:4282

**Comment by arkanif** [comment]
@dmitrymatlah обратите внимание на ошибку
MySQL server has gone away
Ваша СУБД легла в какой-то момент

**Comment by arkanif** [comment]
@dmitrymatlah 
Пожалуйста, перед тем как публиковать стектрейс, удаляйте из него строки вида "#" +"число" — это создаёт ссылки на issue и всех запутывает.
