### ISSUE TITLE
Class 'Bitrix\highloadblock\<...>' not found

### ISSUE THREAD

**Issue by supermike** [intervolga/intervolga.migrato#19]
После установки модуля пытаюсь запустить процедуру "run.php -W" и скрипт выдает ошибку: класс GroupAccessTable не найден. Если убрать из config.xml этот модуль, то ругается уже на HighloadBlock, если убрать HighloadBlock то ругается на HighloadBlockLangTable. Похоже что скрипт не видит классы битрикса. Bitrix 15.5.10. В чем может быть проблема? Куда копать?

Устанавливал в папку Local/modules, потому что если установить в папку bitrix/modules то файл config.xml не создается и вообще я так понял модуль поддерживает установку только в папку local.

**PS. ошибки:** 

> Fatal error: Class 'Bitrix\Catalog\GroupAccessTable' not found in C:\OpenServer\domains\gitrep\example.loc\public_html\local\modules\intervolga.migrato\lib\data\module\catalog\pricetype.php on line 87

> Fatal error: Class 'Bitrix\Highloadblock\HighloadBlockLangTable' not found in C:\OpenServer\domains\gitrep\example.loc\public_html\local\modules\intervolga.migrato\lib\data\module\highloadblock\highloadblock.php on line 52

**Comment by arkanif** [comment]
@supermike, чем более старая версия Bitrix у вас, тем больше сущностей из модуля миграций требуется отключать. Версия Битрикс 15.5 вышла 27 мая 2015, более 4 лет назад.
