### ISSUE TITLE
Интеграция с composer/installers

### ISSUE THREAD

**Issue by yjiotpukc** [intervolga/intervolga.migrato#2]
composer/installers позволит устанавливать ваш модуль через Composer. Достаточно дописать несколько строк в composer.json. Тогда при выполнении команды `composer install` модуль сам установится в папку /bitrix/modules.

[composer/installers](https://github.com/composer/installers)

Дополнительные материалы:
http://bitrix.expert/tekhnologii/bitriks-composer-marketpleys-i-vse-vse-vse/
https://www.youtube.com/watch?v=Q26FertI_wo

**Comment by terick** [comment]
`{"repositories":[

        {
            "type":"package",
            "package":{
                "name":"intervolga/migrato",
                "version":"1.0.0",
                "type": "bitrix-module",
                "extra": {
                    "installer-name": "intervolga.migrato"
                },
                "source":{
                    "type":"git",
                    "url":"https://github.com/intervolga/intervolga.migrato",
                    "reference":"master"
                }
            }
        }
    ],
    "require":{
        "composer/installers": "*",
        "intervolga/migrato":"1.0.0"
    },
    "extra": {
        "bitrix-dir": "public_html/bitrix"
    }
}
`
