### ISSUE TITLE
На сколько важна проверка XML_ID?

### ISSUE THREAD

**Issue by AlexeyBille** [intervolga/intervolga.migrato#22]
Из за русских символов в XML_ID появляются ошибки, почему именно такой паттерн проверки XML_ID выбран? На сколько это важно?
`!!preg_match_all('/^[a-z0-9\-_#.]+$/i', $xmlId, $matches);`

![image](https://user-images.githubusercontent.com/17798452/53283232-a1fe2700-3775-11e9-9721-12da9d954395.png)

**Comment by arkanif** [comment]
@AlexeyBille, эти XML файлы будут храниться в репозитории и путешествовать между разными ОС. Решение запретить кириллицу в XML_ID, а, следовательно, и в названиях файлов, продиктовано стремлением сделать кроссплатформенное решение. В своей инсталляции модуля вы можете расширить состав разрешённых символов на свой страх и риск.
