### ISSUE TITLE
Ошибка в структуре базы данных

### ISSUE THREAD

**Issue by itzavod** [intervolga/intervolga.migrato#23]
Добрый день.

После каждого импорта запускаю проверку сайта и получаю ошибку.

`В таблице b_user_access не хватает служебной записи: insert into b_user_access (USER_ID, PROVIDER_ID, ACCESS_CODE) values (0, 'group', 'G2')`

Самостоятельно обнаружить причину не удалось. 
Версия модуля 0.9.0

**Comment by arkanif** [comment]
Спасибо, проверим

**Comment by arkanif** [comment]
@itzavod, можете прислать zip со своими xml-файлами, назвать версию Битрикса, редакцию, версию PHP? У нас проблема не воспроизводится. выслать можете на erofeev@intervolga.ru

**Comment by arkanif** [comment]
Воспроизвести не удалось, ответа не получили, закрываем
