### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by ikarpovich** [intervolga/intervolga.migrato#24]
Although the module has support for language files there is no English translation done which prevents English speaking users from using the module.

В модуле есть поддержка языковых файлов, но отсутствует английский перевод, что ограничивает использование модуля.

**Comment by arkanif** [comment]
@ikarpovich доля англоязычных программистов, работающих с Битриксом мала. Доля настолько смелых англоязычных прогрограммистов, что они захотят использовать сложные технологии, навроде нашего модуля миграции структуры данных, ещё меньше. Возможность перевести модуль на английский есть (как вы сами отметили, языковые файлы мы поддерживаем).
