### ISSUE TITLE
Ошибка при миграции форм

### ISSUE THREAD

**Issue by tigraldinio** [intervolga/intervolga.migrato#27]
Приветствую.
Разворачиваю демонстрационную версию битрикса и при миграции возникает такая ошибка:
\\\
При выполнении команды произошла ошибка (Класс: Error)
[] operator not supported for stringgs (Код ошибки: 0)
/home/bitrix/www/bitrix/modules/intervolga.migrato/lib/data/module/form/form.php(180)
\\\

Если убрать в конфигурации веб-формы, то всё хорошо.
Ошибку при валидации не отследить.
Как можно её исправить, сохранив миграцию настройки веб-форм

**Comment by arkanif** [comment]
Спасибо, проверим

**Comment by skDYLAN** [comment]
Подтверждаю! Ошибка есть, исправьте плз

**Comment by gafk** [comment]
Исправлено в версии 0.9.5.
