### ISSUE TITLE
Импорт свойства "Дата/время" - умный фильтр

### ISSUE THREAD

**Issue by Druid13** [intervolga/intervolga.migrato#32]
SectionPropertyTable::add($fields)

При попытке добавление свойства с типом "Дата/Время" и "показывать в умном фильтре" с внешним видом "календарь", происходит проверка сам внешний вид.
/bitrix/modules/iblock/lib/sectionpropertytable.php
На 85 строчке прописаны данные типы, а тип календарь ("U") нет, он имеется только как константа.
Получается экспорт работает корректно, а при дальнейшем импорте уже возникает ошибка с валидацией
https://github.com/intervolga/intervolga.migrato/blob/master/lib/data/module/iblock/property.php#L285

**Comment by stasdruid** [comment]
Битрикс поправил через полгода данный метод вызываемый модулем

Через мою заявку
