### ISSUE TITLE
Не работает на php7.1

### ISSUE THREAD

**Issue by xaoc2007** [intervolga/intervolga.migrato#5]
Сейчас не работает. Пришлось откатиться до php7.0.

Скрин ошибки сделать не догадался вовремя, но ошибка легко воспроизводится.

Насколько помню ошибка была в неправильном наследовании:
class Link extends Value

ругался на конструктор.

**Comment by arkanif** [comment]
Спасибо, посмотрим

**Comment by xaoc2007** [comment]
Версия php 7.1.10
![screenshot_20171101_143841](https://user-images.githubusercontent.com/844922/32264704-88d14096-bf12-11e7-9028-af84973fffe4.png)

Ошибка при запуске validate
![screenshot_20171101_143820](https://user-images.githubusercontent.com/844922/32264743-ac51b618-bf12-11e7-9a33-6e98ba9d5f48.png)

Ошибка при запуске validate с ключем -vvv
![screenshot_20171101_143928](https://user-images.githubusercontent.com/844922/32264767-c3c8243a-bf12-11e7-91fb-8b8111933228.png)

**Comment by xaoc2007** [comment]
```
Too few arguments to function Intervolga\Migrato\Data\Link::__construct(), 0 passed in .../modules/intervolga.migrato/lib/data/value.php on line 97 and at least 1 expected (Код ошибки: 0)
Стек вызова:
##.../modules/intervolga.migrato/lib/data/link.php(18)
#0 .../modules/intervolga.migrato/lib/data/value.php(97): Intervolga\Migrato\Data\Link->__construct()
#1 .../modules/intervolga.migrato/lib/tool/datafileviewxml.php(299): Intervolga\Migrato\Data\Value::createMultiple(Array)
#2 .../modules/intervolga.migrato/lib/tool/datafileviewxml.php(212): Intervolga\Migrato\Tool\DataFileViewXml::parseLinks(Array)
```

**Comment by arkanif** [comment]
Спасибо, исправили. Ждите в релизе 0.8.1
