### ISSUE TITLE
Выборка ИБ для экспорта

### ISSUE THREAD

**Issue by NiGP** [intervolga/intervolga.migrato#7]
Ребята, что то не могу разобраться никак, как ограничить export миграции, например, только для ИБ с IBLOCK_CODE=map?

**Comment by arkanif** [comment]
Добрый день! С помощью модуля вы можете либо мигрировать все ИБ, либо ни один. Фильтр стоит в планах, но задача не приоритетная.

**Comment by pr0n1x** [comment]
+ тут очень много начинает зависеть от разработчика. А вдруг в фильтр вы запихаете важный для цепочки зависимостей ИБ. Проблемы начнутся 100%. А зачем фильтр? Интересно что с этого может получиться, но проверять почему-то не хочется.

**Comment by xaoc2007** [comment]
Внесу свои 5коп в обсуждение.
@pr0n1x 
Считаю функционал нужным. 
Иногда работа ведется над двумя задачами, и обе пока рано выливать куда то. Для каждой задачи созданы свои инфоблоки.
Поднимать сайт со своей базой под каждую задачу - ну такое.. 

Если я хочу вылить только одну из задач, то придется выливать все инфоблоки, в том числе и от другой задачи.

С одной стороны - ну и пофиг, они же нигде не участвуют, код второй задачи же я не вылил.
С другой стороны - мало ли на что-то может повлиять, да и засорять базу прода ненужными инфоблоками не хорошо.

Поделитесь опытом, кстати, как поступаете в подобных ситуациях.

Согласен, что могут быть нюансы, что разработчик сам должен думать, если применяет такое. Но как бы разработчик в принципе должен думать.

Подобная гибкость могла бы быть полезной во многих случаях.
